package com.habitat.api.storage;

import org.springframework.web.multipart.MultipartFile;

import java.util.Set;

/**
 * Pluggable file storage. The interface is intentionally small so the
 * {@link LocalStorageService} dev implementation and a future S3 impl
 * can satisfy it without leaking provider details.
 *
 * <h2>Contracts</h2>
 *
 * <ul>
 *   <li>{@link #store} runs Apache Tika magic-byte detection before
 *       writing. {@code allowedMimeTypes} is the whitelist; the caller's
 *       {@code Content-Type} header is ignored (it's client-spoofable,
 *       per {@code development-standards.md} §6).</li>
 *   <li>{@code maxBytes} caps payload size; oversize uploads fail with
 *       {@link com.habitat.api.constants.ErrorMessages#FILE_TOO_LARGE}.</li>
 *   <li>{@link #open} and {@link #delete} both normalise the supplied
 *       path and reject any input that escapes the storage root. This
 *       is the defence-in-depth requirement from §6.</li>
 *   <li>Returned {@link StoredFile#storedPath} is opaque to callers —
 *       always pass it back to this service to read/delete the file.</li>
 * </ul>
 */
public interface StorageService {

    /**
     * Validate + persist a multipart upload.
     *
     * @param folder           one of {@link com.habitat.api.constants.StorageConstants}
     *                         folder constants (e.g. {@code "documents"}).
     * @param file             the multipart payload — must be non-null and non-empty.
     * @param allowedMimeTypes the magic-byte-detected MIME types accepted for this folder.
     * @param maxBytes         hard cap on payload size in bytes.
     */
    StoredFile store(String folder,
                     MultipartFile file,
                     Set<String> allowedMimeTypes,
                     long maxBytes);

    /**
     * Persist server-generated bytes (e.g. a rendered lease PDF) without
     * Tika validation or a configurable size cap. The bytes are trusted
     * by definition — the API just produced them — so the validation
     * pass that {@link #store} runs would be redundant.
     */
    StoredFile storeTrustedBytes(String folder, String filename, String mimeType, byte[] bytes);

    /**
     * Open a previously stored file. The caller must have already
     * performed any ownership / authorisation checks.
     */
    StoredResource open(String storedPath);

    /**
     * Delete a previously stored file. Idempotent — missing files are
     * a no-op so reupload-then-cleanup paths can be straight-line.
     */
    void delete(String storedPath);

    /**
     * Cheap existence check without opening the file. Used by tests
     * and admin diagnostics.
     */
    boolean exists(String storedPath);
}
